# Generated by Django 3.2.5 on 2021-10-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaseinfo',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
