# Generated by Django 3.2.5 on 2021-10-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_releaseinfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaseinfo',
            name='DuplicateCheckCanIgnore',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='releaseinfo',
            name='FinishedJobPhase',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='releaseinfo',
            name='Flags',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='releaseinfo',
            name='JobRunningState',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='releaseinfo',
            name='JobStartMode',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='releaseinfo',
            name='Size',
            field=models.IntegerField(default=0),
        ),
    ]
