# Generated by Django 3.2.5 on 2021-10-29 20:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20211029_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaseinfo',
            name='ScheduleTimeUtc',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='releaseinfo',
            name='Subtitles',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='releaseinfo',
            name='Trumpable',
            field=models.JSONField(default=[]),
        ),
    ]
