# Generated by Django 3.2.5 on 2021-10-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20211029_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaseinfo',
            name='Trumpable',
            field=models.JSONField(default=list),
        ),
    ]
