# Generated by Django 3.2.16 on 2023-01-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_releaseinfo_bdinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseinfo',
            name='IncludedFileList',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
